<a href="https://colab.research.google.com/github/Shambhavi-Gupta/numpy_questions/blob/master/numpy_questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a=np.array([1,2,3,4])
a[0]=0.9
print(a[0],a.dtype)

0 int64


In [3]:
import numpy as np
a=np.array([1.0,2.2,3.5])
a=a/0.0
print(a[0])

inf


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [4]:
a=np.arange(10)
b=np.where(a%2==1,1,a)
print(b)

[0 1 2 1 4 1 6 1 8 1]


In [6]:
a=np.array([3,6,9,12,15])
b=np.array([2,4,6,8,12])
c=np.where(a==b)
print(c[0])

[]


In [7]:
a=np.array([1,2,3,4,5])
print(a[: : -1])

[5 4 3 2 1]


In [8]:
a=np.array([1,2,3,4,5])
print(a[2 : None])

[3 4 5]


In [9]:
a=np.array([[1,2,3],[4,5,6]])
print(a[1][2])

6
